export { default as Call } from './Call'
export { default as Consulting } from './Consulting'
export { default as Email } from './Email'
export { default as Farmer } from './Farmer'
export { default as Money } from './Money'
export { default as SokosolutionSvg } from './SokosolutionSvg'